#!/usr/bin/fish
set path "$argv[1]"
clear
if test -f "$path"
    kitty icat $path
end
while true
    inotifywait (path dirname $path) -q -e close_write | read dir action file
    if test "$file" = (path basename $path)
        tput cup 0 0
        kitty icat "$dir$file"
    end
end


